### ISSUE TITLE
The "entryId" passed to the browser plugin is wrong on Windows

### ISSUE THREAD

**Issue by AurelienStebe** [marko-js/rollup#11]
### Details

My GitHub CI workflow reported this error on Windows :

`Invalid substitution "D:\a\gladejs\gladejs\tests\minimal\build\index_4c93" for placeholder "[name]" in "output.entryFileNames" pattern, can be neither absolute nor relative path.`

https://github.com/gladejs/gladejs/runs/2451848465?check_suite_focus=true#step:4:37

Looking at the implementation of `toEntryId()`, it doesn't take into account Windows backslashes.

https://github.com/marko-js/rollup/blob/f4ecbaf694c53b54721902dd5b1452cd2990632f/src/index.ts#L572-L579

### Expected Behavior

The output of `toEntryId()` should be the same on any OS.

### Possible Fix

Change the RegEx on line 575 or maybe call "normalize-path" on the filename first.

### Your Environment

The environment is detailed in the GitHub Action linked above.
Note that only NodeJS v15 gave a clear error message, NodeJS v14 & v16 gave me timeouts, which might not be related to "@marko/rollup", I'm not sure yet.

### Steps to Reproduce

Any linked config should give the same result on Windows, but I have not created a reduced test case.

**Comment by DylanPiercey** [comment]
Good catch, thanks for creating the issue! For some reason I decided to re-implement our entry id generation logic and sure enough I broke windows. I've gone ahead and released `@marko/rollup@3.1.1` with the same entry id generation logic as our webpack plugin which should not have this issue.
