### ISSUE TITLE
Linked config in "--watch" mode runs the browser side twice on file change

### ISSUE THREAD

**Issue by AurelienStebe** [marko-js/rollup#12]
### Details

Using a linked config and the Rollup "--watch" flag, when a Marko "page" is modified the server-side runs once (good) and then the browser-side runs twice (not so good). So, it works fine, but it is slower than it should be.

### Possible Fix

Commenting out line 462 below (not watching the `serverEntriesFile`) fixes the issue.

https://github.com/marko-js/rollup/blob/f4ecbaf694c53b54721902dd5b1452cd2990632f/src/index.ts#L456-L463

### Explanation

Note that it doesn't seem to be an issue if modifying a Marko file that is only compiled (and hence watched) by the server-side, or only by the client-side. However, modifying a Marko "page" will be detected by both sides and will queue a re-run for both sides.
The server-side goes first and modifies the `serverEntriesFile` in its `generateBundle()` hook, queuing another browser-side re-run. The browser-side runs for the Marko "page" change and then runs another time for the `serverEntriesFile` change.

### Your Environment

- Environment name and version: NodeJS v14.16.1 on MacOS
- Link to your project: https://github.com/gladejs/gladejs

**Comment by DylanPiercey** [comment]
I just got out (another) release, `@marko/rollup@3.2.0` which now avoids writing to this server entries file unless the server entries change. This should mean that the browser is invalidated less often.

I think there are more cases that would have this "runs twice" issue though, basically any component that is actually loaded in both the server and browser. The release I just did though should at least mean that top level server only templates (the browser entrypoints) are no longer invalidate both builds.

**Comment by AurelienStebe** [comment]
Completely agree with you, there are other cases and fixing that one is enough.
That ticket is barely a bug report and more of a "nice to have" perf optimisation.

Anyway, just copy/pasting your own solution from Discord for what is missing around line 346 :
```
hasNewServerEntries ||= serverEntries[entryId] !== fileName;
serverEntries[entryId] = fileName;
```
