### ISSUE TITLE
The order of the "rollup" tag parameters is not guaranteed in multiple outputs builds

### ISSUE THREAD

**Issue by AurelienStebe** [marko-js/rollup#13]
### Details

When using multiple `output` options inside the browser-side build of a linked config, the order of the `<rollup>` tag parameters is not guaranteed, because Rollup executes multiple outputs in parallel.

https://github.com/rollup/rollup/blob/8c59abec02bf1cdf88873a73581a56a7beb68f1d/cli/run/build.ts#L64

So depending on which one finishes first, the template might get
`<rollup|entry, output_1, output_2|>` or `<rollup|entry, output_2, output_1|>`.

### Possible Fix

I'm using this in my own framework to keep track of which output is which :
https://github.com/gladejs/gladejs/blob/3ea219e3641b7cae54c210a2e2c2a260f7992816/packages/rollup/src/gladejs-browser.js#L13-L16

---

I quickly hacked the following lines directly in my "node_modules" folder to speed up my tests :

In the `browserPlugin` I modified those two hooks.

```
async options(inputOptions) {
  outputDirs = inputOptions.output.map(it => it.dir);
```
(don't try that in the `buildStart()` hook, it doesn't get the output options for some reason)

```
async writeBundle(outputOptions, bundle) {
  const index = outputDirs.findIndex(it => it === outputOptions.dir)
```
(the above should probably use `it.dir ?? path.dirname(it.file)` to support all types of config)

Then, simply pass the `index` to the modified `channel.getBundleWriter().write()`.
```
async write(bundle, index) {
  bundles[index] = bundle;

  if (!bundles.find(it => it === PENDING_MARKER)) {
```

I haven't tried to use multiple browser-side builds, but those run sequentially anyway.

**Comment by DylanPiercey** [comment]
Fix is released in `3.2.1` 😄
